MANC notebook- create csv annotation fiels for MANC in version 1.2.3. 2026 04 03

In [19]:
# set up environment
import sys
import json
import re
import requests
import pandas as pd
from pathlib import Path
import json

from caveclient import CAVEclient

import urllib.parse


print("Python executable:", sys.executable)
print("Imports OK")

Python executable: c:\Users\jsfdz\Documents\Python\cave_env\Scripts\python.exe
Imports OK

In [16]:
from pathlib import Path
import json

# set up directories
PROJECT_ROOT = Path.cwd()

INPUT_DIR = PROJECT_ROOT / "output"
if not INPUT_DIR.exists():
    raise FileNotFoundError(f"Input directory missing: {INPUT_DIR}")

OUTPUT_DIR = PROJECT_ROOT / "output-MANCv1.2.3_04B_morphology_clusters_T1"
OUTPUT_DIR.mkdir(exist_ok=True)

print("Input:", INPUT_DIR)
print("Output:", OUTPUT_DIR)

# load input state
STATE_IN = INPUT_DIR / "manc_v1p2_with_manual_IR_layers.json"
if not STATE_IN.exists():
    raise FileNotFoundError(f"Missing state file: {STATE_IN}")

with open(STATE_IN, "r", encoding="utf-8") as f:
    state = json.load(f)

# save output state
STATE_OUT = OUTPUT_DIR / "manc_4b_morphology_clusters_jhs.json"

with open(STATE_OUT, "w", encoding="utf-8") as f:
    json.dump(state, f, indent=2)

Input: c:\Users\jsfdz\4B-analysis\4B-analysis\output
Output: c:\Users\jsfdz\4B-analysis\4B-analysis\output-MANCv1.2.3_04B_morphology_clusters_T1

In [14]:
# build a simple descriptive CSV to describe the state view
import json
import csv
import re

# ---- LOAD INPUT STATE (read only) ----
with open(STATE_IN, "r", encoding="utf-8") as f:
    state = json.load(f)

# ---- PREP OUTPUT ----
state_title = state.get("title", "untitled_state")
safe_title = re.sub(r"[^a-zA-Z0-9_-]+", "_", state_title)

OUT_CSV = OUTPUT_DIR / f"{safe_title}_layer_annotations.csv"

# ---- EXTRACT LAYERS ----
rows = []

for L in state.get("layers", []):
    layer_type = L.get("type", "")
    name = L.get("name", "")
    visible = L.get("visible", "")

    segments = L.get("segments", [])
    segments_IDs = ",".join(str(s) for s in segments) if segments else ""

    seg_colors = L.get("segmentColors") or {}
    unique_colors = set(seg_colors.values())
    layer_color = list(unique_colors)[0] if len(unique_colors) == 1 else ""

    rows.append({
        "state_title": state_title,
        "layer_name": name,
        "layer_type": layer_type,
        "visible": visible,
        "layer_color": layer_color,
        "num_segments": len(segments),
        "segments_IDs": segments_IDs,
        "note": ""
    })

# ---- WRITE CSV ----
fieldnames = [
    "state_title",
    "layer_name",
    "layer_type",
    "visible",
    "layer_color",
    "num_segments",
    "segments_IDs",
    "note",
]

# define output filename based on input state
OUT_CSV = OUTPUT_DIR / f"{STATE_IN.stem}_layer_summary.csv"

# write CSV
with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote summary of {STATE_IN.name} → {OUT_CSV.name}")

Wrote summary of manc_v1p2_with_manual_IR_layers.json → manc_v1p2_with_manual_IR_layers_layer_summary.csv

Make a csv with neuron as row, and grouped by sefment alyer, and add info liek segment ID and MANC type

In [15]:
# build a CSV mapping segment IDs to manual morphology clusters
import json
import csv

# ---- LOAD INPUT STATE ----
with open(STATE_IN, "r", encoding="utf-8") as f:
    state = json.load(f)

# ---- DEFINE OUTPUT ----
OUT_CSV = OUTPUT_DIR / f"{STATE_IN.stem}_manual_clusters_by_segment.csv"

rows = []

state_title = state.get("title", "untitled_state")

# ---- EXTRACT PER-SEGMENT DATA ----
for L in state.get("layers", []):
    layer_name = L.get("name", "")
    layer_type = L.get("type", "")
    visible = L.get("visible", "")

    segments = L.get("segments", [])

    for seg_id in segments:
        rows.append({
            "state_title": state_title,
            "segment_id": str(seg_id),
            "manual_morphology_cluster": layer_name,
            "manc_type": "",  # to be filled later
            "layer_type": layer_type,
            "visible": visible,
            "note": ""
        })

# ---- WRITE CSV ----
fieldnames = [
    "state_title",
    "segment_id",
    "manual_morphology_cluster",
    "manc_type",
    "layer_type",
    "visible",
    "note",
]

with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote segment → cluster mapping: {OUT_CSV.name}")

Wrote segment → cluster mapping: manc_v1p2_with_manual_IR_layers_manual_clusters_by_segment.csv

Lets make a table for the layers of interest only

In [ ]:

# Build one master DataFrame with one row per segment ID
import json
import pandas as pd

# ---- LOAD INPUT STATE ----
with open(STATE_IN, "r", encoding="utf-8") as f:
    state = json.load(f)

rows = []

for L in state.get("layers", []):
    layer_name = L.get("name", "")
    layer_type = L.get("type", "")
    visible = L.get("visible", "")
    segment_ids = L.get("segments", []) or []

    if layer_type != "segmentation":
        continue
    if not segment_ids:
        continue

    for seg_id in segment_ids:
        rows.append({
            "manual_morphology_cluster": layer_name,
            "layer_type": layer_type,
            "visible": visible,
            "segment_id": int(seg_id),
            "manc_type": "",   # fill later
            "note": ""
        })

all_layers_df = (
    pd.DataFrame(rows)
    .drop_duplicates()
    .sort_values(["manual_morphology_cluster", "segment_id"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

all_layers_df

,manual_morphology_cluster,layer_type,visible,segment_id,manc_type,note
0,all-synaptic,segmentation,,1,,
1,all-tissue,segmentation,False,1,,
2,court et al. tracts,segmentation,,100,,
3,court et al. tracts,segmentation,,101,,
4,court et al. tracts,segmentation,,102,,
5,court et al. tracts,segmentation,,103,,
6,court et al. tracts,segmentation,,104,,
7,court et al. tracts,segmentation,,105,,
8,court et al. tracts,segmentation,,106,,
9,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,21862,,
10,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,152655,,
11,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,166421,,
12,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,17567,,
13,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,17572,,
14,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,18156,,
15,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,18785,,
16,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,20077,,
17,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,21567,,
18,manc-seg-v1.2 4B manual IR-nomorphology assig...,segmentation,False,101453,,
19,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13455,,
20,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13506,,
21,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13589,,
22,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,14728,,
23,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,14774,,
24,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,15005,,
25,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,10024,,
26,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,12523,,
27,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,16487,,
28,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,16527,,
29,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17351,,
30,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17409,,
31,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17534,,
32,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,18571,,
33,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,101447,,
34,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,162540,,
35,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,15002,,
36,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,18755,,
37,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,155236,,
38,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,164102,,
39,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,18156,,
40,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,22868,,
41,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,23716,,
42,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,26941,,
43,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,27760,,
44,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,38071,,
45,manc-seg-v1.2 4B manual IR nomorphology assign...,segmentation,,164146,,
46,manc-seg-v1.2 4B manual IR-1,segmentation,True,18156,,
47,manc-seg-v1.2 4B manual IR-1,segmentation,True,18253,,
48,manc-seg-v1.2 4B manual IR-1,segmentation,True,18629,,
49,manc-seg-v1.2 4B manual IR-1,segmentation,True,19833,,
50,manc-seg-v1.2 4B manual IR-1,segmentation,True,21189,,
51,manc-seg-v1.2 4B manual IR-1,segmentation,True,21322,,
52,manc-seg-v1.2 4B manual IR-1,segmentation,True,22868,,
53,manc-seg-v1.2 4B manual IR-1,segmentation,True,23716,,
54,manc-seg-v1.2 4B manual IR-1,segmentation,True,24181,,
55,manc-seg-v1.2 4B manual IR-1,segmentation,True,26941,,
56,manc-seg-v1.2 4B manual IR-1,segmentation,True,27760,,
57,manc-seg-v1.2 4B manual IR-1,segmentation,True,38071,,
58,manc-seg-v1.2 4B manual IR-1,segmentation,True,102138,,
59,manc-seg-v1.2 4B manual IR-1,segmentation,True,102536,,
60,manc-seg-v1.2 4B manual IR-1,segmentation,True,164146,,
61,manc-seg-v1.2 4B manual IR-2,segmentation,True,18641,,
62,manc-seg-v1.2 4B manual IR-2,segmentation,True,18990,,
63,manc-seg-v1.2 4B manual IR-2,segmentation,True,21499,,
64,manc-seg-v1.2 4B manual IR-2,segmentation,True,22163,,
65,manc-seg-v1.2 4B manual IR-2,segmentation,True,22997,,
66,manc-seg-v1.2 4B manual IR-2,segmentation,True,29988,,
67,manc-seg-v1.2 4B manual IR-2,segmentation,True,100525,,
68,manc-seg-v1.2 4B manual IR-2,segmentation,True,153878,,
69,manc-seg-v1.2 4B manual IR-2,segmentation,True,165318,,
70,manc-seg-v1.2 4B manual IR-3,segmentation,True,17567,,
71,manc-seg-v1.2 4B manual IR-3,segmentation,True,17935,,
72,manc-seg-v1.2 4B manual IR-4,segmentation,True,17572,,
73,manc-seg-v1.2 4B manual IR-4,segmentation,True,18785,,
74,manc-seg-v1.2 4B manual IR-4,segmentation,True,20077,,
75,manc-seg-v1.2 4B manual IR-4,segmentation,True,21567,,
76,manc-seg-v1.2 4B manual IR-4,segmentation,True,101453,,
77,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,16224,,
78,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,20836,,
79,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,26388,,
80,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,100339,,
81,manc-seg-v1.2 4B- primary n=4,segmentation,False,11143,,
82,manc-seg-v1.2 4B- primary n=4,segmentation,False,12523,,
83,manc-seg-v1.2 4B- primary n=4,segmentation,False,13436,,
84,manc-seg-v1.2 4B- primary n=4,segmentation,False,17395,,
85,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,15309,,
86,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,18148,,
87,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,19250,,
88,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,19366,,
89,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,21956,,
90,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,152244,,
91,manc-seg-v1.2-4B-all,segmentation,,10024,,
92,manc-seg-v1.2-4B-all,segmentation,,10314,,
93,manc-seg-v1.2-4B-all,segmentation,,11143,,
94,manc-seg-v1.2-4B-all,segmentation,,12523,,
95,manc-seg-v1.2-4B-all,segmentation,,13128,,
96,manc-seg-v1.2-4B-all,segmentation,,13409,,
97,manc-seg-v1.2-4B-all,segmentation,,13436,,
98,manc-seg-v1.2-4B-all,segmentation,,13455,,
99,manc-seg-v1.2-4B-all,segmentation,,13506,,
100,manc-seg-v1.2-4B-all,segmentation,,13589,,
101,manc-seg-v1.2-4B-all,segmentation,,13770,,
102,manc-seg-v1.2-4B-all,segmentation,,13798,,
103,manc-seg-v1.2-4B-all,segmentation,,13975,,
104,manc-seg-v1.2-4B-all,segmentation,,14024,,
105,manc-seg-v1.2-4B-all,segmentation,,14031,,
106,manc-seg-v1.2-4B-all,segmentation,,14389,,
107,manc-seg-v1.2-4B-all,segmentation,,14697,,
108,manc-seg-v1.2-4B-all,segmentation,,14728,,
109,manc-seg-v1.2-4B-all,segmentation,,14774,,
110,manc-seg-v1.2-4B-all,segmentation,,14954,,
111,manc-seg-v1.2-4B-all,segmentation,,15002,,
112,manc-seg-v1.2-4B-all,segmentation,,15005,,
113,manc-seg-v1.2-4B-all,segmentation,,15309,,
114,manc-seg-v1.2-4B-all,segmentation,,15393,,
115,manc-seg-v1.2-4B-all,segmentation,,15401,,
116,manc-seg-v1.2-4B-all,segmentation,,15811,,
117,manc-seg-v1.2-4B-all,segmentation,,15969,,
118,manc-seg-v1.2-4B-all,segmentation,,16224,,
119,manc-seg-v1.2-4B-all,segmentation,,16293,,
120,manc-seg-v1.2-4B-all,segmentation,,16487,,
121,manc-seg-v1.2-4B-all,segmentation,,16527,,
122,manc-seg-v1.2-4B-all,segmentation,,16757,,
123,manc-seg-v1.2-4B-all,segmentation,,17351,,
124,manc-seg-v1.2-4B-all,segmentation,,17395,,
125,manc-seg-v1.2-4B-all,segmentation,,17409,,
126,manc-seg-v1.2-4B-all,segmentation,,17490,,
127,manc-seg-v1.2-4B-all,segmentation,,17534,,
128,manc-seg-v1.2-4B-all,segmentation,,17567,,
129,manc-seg-v1.2-4B-all,segmentation,,17572,,
130,manc-seg-v1.2-4B-all,segmentation,,17678,,
131,manc-seg-v1.2-4B-all,segmentation,,17935,,
132,manc-seg-v1.2-4B-all,segmentation,,18148,,
133,manc-seg-v1.2-4B-all,segmentation,,18156,,
134,manc-seg-v1.2-4B-all,segmentation,,18253,,
135,manc-seg-v1.2-4B-all,segmentation,,18571,,
136,manc-seg-v1.2-4B-all,segmentation,,18605,,
137,manc-seg-v1.2-4B-all,segmentation,,18629,,
138,manc-seg-v1.2-4B-all,segmentation,,18641,,
139,manc-seg-v1.2-4B-all,segmentation,,18724,,
140,manc-seg-v1.2-4B-all,segmentation,,18755,,
141,manc-seg-v1.2-4B-all,segmentation,,18785,,
142,manc-seg-v1.2-4B-all,segmentation,,18831,,
143,manc-seg-v1.2-4B-all,segmentation,,18990,,
144,manc-seg-v1.2-4B-all,segmentation,,19250,,
145,manc-seg-v1.2-4B-all,segmentation,,19366,,
146,manc-seg-v1.2-4B-all,segmentation,,19833,,
147,manc-seg-v1.2-4B-all,segmentation,,19912,,
148,manc-seg-v1.2-4B-all,segmentation,,19985,,
149,manc-seg-v1.2-4B-all,segmentation,,20077,,
150,manc-seg-v1.2-4B-all,segmentation,,20585,,
151,manc-seg-v1.2-4B-all,segmentation,,20836,,
152,manc-seg-v1.2-4B-all,segmentation,,20932,,
153,manc-seg-v1.2-4B-all,segmentation,,21189,,
154,manc-seg-v1.2-4B-all,segmentation,,21322,,
155,manc-seg-v1.2-4B-all,segmentation,,21499,,
156,manc-seg-v1.2-4B-all,segmentation,,21567,,
157,manc-seg-v1.2-4B-all,segmentation,,21808,,
158,manc-seg-v1.2-4B-all,segmentation,,21862,,
159,manc-seg-v1.2-4B-all,segmentation,,21956,,
160,manc-seg-v1.2-4B-all,segmentation,,22163,,
161,manc-seg-v1.2-4B-all,segmentation,,22868,,
162,manc-seg-v1.2-4B-all,segmentation,,22997,,
163,manc-seg-v1.2-4B-all,segmentation,,23716,,
164,manc-seg-v1.2-4B-all,segmentation,,23790,,
165,manc-seg-v1.2-4B-all,segmentation,,24181,,
166,manc-seg-v1.2-4B-all,segmentation,,26388,,
167,manc-seg-v1.2-4B-all,segmentation,,26941,,
168,manc-seg-v1.2-4B-all,segmentation,,27760,,
169,manc-seg-v1.2-4B-all,segmentation,,29988,,
170,manc-seg-v1.2-4B-all,segmentation,,36722,,
171,manc-seg-v1.2-4B-all,segmentation,,38071,,
172,manc-seg-v1.2-4B-all,segmentation,,100339,,
173,manc-seg-v1.2-4B-all,segmentation,,100525,,
174,manc-seg-v1.2-4B-all,segmentation,,101447,,
175,manc-seg-v1.2-4B-all,segmentation,,101453,,
176,manc-seg-v1.2-4B-all,segmentation,,102138,,
177,manc-seg-v1.2-4B-all,segmentation,,102536,,
178,manc-seg-v1.2-4B-all,segmentation,,152244,,
179,manc-seg-v1.2-4B-all,segmentation,,152655,,
180,manc-seg-v1.2-4B-all,segmentation,,153878,,
181,manc-seg-v1.2-4B-all,segmentation,,155236,,
182,manc-seg-v1.2-4B-all,segmentation,,158391,,
183,manc-seg-v1.2-4B-all,segmentation,,162540,,
184,manc-seg-v1.2-4B-all,segmentation,,164102,,
185,manc-seg-v1.2-4B-all,segmentation,,164146,,
186,manc-seg-v1.2-4B-all,segmentation,,165318,,
187,manc-seg-v1.2-4B-all,segmentation,,166421,,
188,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,10314,,
189,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,11143,,
190,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,13436,,
191,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,14031,,
192,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15393,,
193,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15401,,
194,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15969,,
195,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,16293,,
196,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,17395,,
197,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,19912,,
198,manc-seg-v1.2-4B-sublass IR n=60,segmentation,False,13409,,
199,manc-seg-v1.21- secondary n=73,segmentation,False,10024,,
200,manc-seg-v1.21- secondary n=73,segmentation,False,13128,,
201,manc-seg-v1.21- secondary n=73,segmentation,False,13409,,
202,manc-seg-v1.21- secondary n=73,segmentation,False,13455,,
203,manc-seg-v1.21- secondary n=73,segmentation,False,13506,,
204,manc-seg-v1.21- secondary n=73,segmentation,False,13589,,
205,manc-seg-v1.21- secondary n=73,segmentation,False,13770,,
206,manc-seg-v1.21- secondary n=73,segmentation,False,13798,,
207,manc-seg-v1.21- secondary n=73,segmentation,False,13975,,
208,manc-seg-v1.21- secondary n=73,segmentation,False,14024,,
209,manc-seg-v1.21- secondary n=73,segmentation,False,14031,,
210,manc-seg-v1.21- secondary n=73,segmentation,False,14697,,
211,manc-seg-v1.21- secondary n=73,segmentation,False,14728,,
212,manc-seg-v1.21- secondary n=73,segmentation,False,14774,,
213,manc-seg-v1.21- secondary n=73,segmentation,False,14954,,
214,manc-seg-v1.21- secondary n=73,segmentation,False,15005,,
215,manc-seg-v1.21- secondary n=73,segmentation,False,15393,,
216,manc-seg-v1.21- secondary n=73,segmentation,False,15401,,
217,manc-seg-v1.21- secondary n=73,segmentation,False,16224,,
218,manc-seg-v1.21- secondary n=73,segmentation,False,16293,,
219,manc-seg-v1.21- secondary n=73,segmentation,False,16487,,
220,manc-seg-v1.21- secondary n=73,segmentation,False,16527,,
221,manc-seg-v1.21- secondary n=73,segmentation,False,17409,,
222,manc-seg-v1.21- secondary n=73,segmentation,False,17534,,
223,manc-seg-v1.21- secondary n=73,segmentation,False,17567,,
224,manc-seg-v1.21- secondary n=73,segmentation,False,17935,,
225,manc-seg-v1.21- secondary n=73,segmentation,False,18148,,
226,manc-seg-v1.21- secondary n=73,segmentation,False,18156,,
227,manc-seg-v1.21- secondary n=73,segmentation,False,18253,,
228,manc-seg-v1.21- secondary n=73,segmentation,False,18571,,
229,manc-seg-v1.21- secondary n=73,segmentation,False,18605,,
230,manc-seg-v1.21- secondary n=73,segmentation,False,18629,,
231,manc-seg-v1.21- secondary n=73,segmentation,False,18641,,
232,manc-seg-v1.21- secondary n=73,segmentation,False,18724,,
233,manc-seg-v1.21- secondary n=73,segmentation,False,18755,,
234,manc-seg-v1.21- secondary n=73,segmentation,False,18990,,
235,manc-seg-v1.21- secondary n=73,segmentation,False,19250,,
236,manc-seg-v1.21- secondary n=73,segmentation,False,19366,,
237,manc-seg-v1.21- secondary n=73,segmentation,False,19833,,
238,manc-seg-v1.21- secondary n=73,segmentation,False,19985,,
239,manc-seg-v1.21- secondary n=73,segmentation,False,20585,,
240,manc-seg-v1.21- secondary n=73,segmentation,False,20836,,
241,manc-seg-v1.21- secondary n=73,segmentation,False,20932,,
242,manc-seg-v1.21- secondary n=73,segmentation,False,21189,,
243,manc-seg-v1.21- secondary n=73,segmentation,False,21322,,
244,manc-seg-v1.21- secondary n=73,segmentation,False,21499,,
245,manc-seg-v1.21- secondary n=73,segmentation,False,21808,,
246,manc-seg-v1.21- secondary n=73,segmentation,False,21862,,
247,manc-seg-v1.21- secondary n=73,segmentation,False,22163,,
248,manc-seg-v1.21- secondary n=73,segmentation,False,22868,,
249,manc-seg-v1.21- secondary n=73,segmentation,False,22997,,
250,manc-seg-v1.21- secondary n=73,segmentation,False,23716,,
251,manc-seg-v1.21- secondary n=73,segmentation,False,23790,,
252,manc-seg-v1.21- secondary n=73,segmentation,False,24181,,
253,manc-seg-v1.21- secondary n=73,segmentation,False,26388,,
254,manc-seg-v1.21- secondary n=73,segmentation,False,26941,,
255,manc-seg-v1.21- secondary n=73,segmentation,False,27760,,
256,manc-seg-v1.21- secondary n=73,segmentation,False,29988,,
257,manc-seg-v1.21- secondary n=73,segmentation,False,36722,,
258,manc-seg-v1.21- secondary n=73,segmentation,False,38071,,
259,manc-seg-v1.21- secondary n=73,segmentation,False,100339,,
260,manc-seg-v1.21- secondary n=73,segmentation,False,100525,,
261,manc-seg-v1.21- secondary n=73,segmentation,False,101447,,
262,manc-seg-v1.21- secondary n=73,segmentation,False,102138,,
263,manc-seg-v1.21- secondary n=73,segmentation,False,102536,,
264,manc-seg-v1.21- secondary n=73,segmentation,False,152244,,
265,manc-seg-v1.21- secondary n=73,segmentation,False,152655,,
266,manc-seg-v1.21- secondary n=73,segmentation,False,153878,,
267,manc-seg-v1.21- secondary n=73,segmentation,False,158391,,
268,manc-seg-v1.21- secondary n=73,segmentation,False,164102,,
269,manc-seg-v1.21- secondary n=73,segmentation,False,164146,,
270,manc-seg-v1.21- secondary n=73,segmentation,False,165318,,
271,manc-seg-v1.21- secondary n=73,segmentation,False,166421,,
272,manc-seg-v1.21-4B subclass BA n=1,segmentation,False,17490,,
273,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,15309,,
274,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,18148,,
275,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,19250,,
276,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,19366,,
277,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,21956,,
278,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,152244,,
279,manc-seg-v1.22-4B subclass IA=4,segmentation,False,10314,,
280,manc-seg-v1.22-4B subclass IA=4,segmentation,False,13436,,
281,manc-seg-v1.22-4B subclass IA=4,segmentation,False,17395,,
282,manc-seg-v1.22-4B subclass IA=4,segmentation,False,19912,,
283,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,10314,,
284,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,14389,,
285,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,15002,,
286,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,15309,,
287,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,15811,,
288,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,15969,,
289,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,16757,,
290,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,17351,,
291,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,17490,,
292,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,17572,,
293,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,17678,,
294,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,18785,,
295,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,18831,,
296,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,19912,,
297,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,20077,,
298,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,21567,,
299,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,21956,,
300,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,101453,,
301,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,155236,,
302,manc-seg-v1.22-4B-early secondary n= 20,segmentation,False,162540,,
303,manc:v1.2.1-TTMn,segmentation,False,10068,,
304,nerves,segmentation,False,1,,
305,nerves,segmentation,False,2,,
306,nerves,segmentation,False,3,,
307,nerves,segmentation,False,4,,
308,nerves,segmentation,False,5,,
309,nerves,segmentation,False,6,,
310,nerves,segmentation,False,7,,
311,nerves,segmentation,False,8,,
312,nerves,segmentation,False,9,,
313,nerves,segmentation,False,10,,
314,nerves,segmentation,False,11,,
315,nerves,segmentation,False,12,,
316,nerves,segmentation,False,13,,
317,nerves,segmentation,False,14,,
318,nerves,segmentation,False,15,,
319,nerves,segmentation,False,16,,
320,nerves,segmentation,False,17,,
321,nerves,segmentation,False,18,,
322,nerves,segmentation,False,19,,
323,nerves,segmentation,False,20,,
324,nerves,segmentation,False,21,,
325,nerves,segmentation,False,22,,
326,nerves,segmentation,False,23,,
327,nerves,segmentation,False,24,,
328,nerves,segmentation,False,25,,
329,nerves,segmentation,False,26,,
330,nerves,segmentation,False,27,,
331,nerves,segmentation,False,28,,
332,nerves,segmentation,False,29,,
333,nerves,segmentation,False,30,,
334,nerves,segmentation,False,31,,
335,nerves,segmentation,False,32,,
336,nerves,segmentation,False,33,,
337,nerves,segmentation,False,34,,
338,nerves,segmentation,False,35,,
339,neuropils,segmentation,,4,,
340,neuropils,segmentation,,5,,
341,neuropils,segmentation,,6,,
342,neuropils,segmentation,,7,,
343,neuropils,segmentation,,8,,
344,neuropils,segmentation,,9,,
345,neuropils,segmentation,,10,,
346,neuropils,segmentation,,11,,
347,neuropils,segmentation,,12,,
348,neuropils,segmentation,,13,,
349,neuropils,segmentation,,14,,
350,neuropils,segmentation,,15,,
351,neuropils,segmentation,,16,,
352,neuropils,segmentation,,17,,
353,neuropils,segmentation,,18,,
354,neuropils,segmentation,,19,,
355,neuropils,segmentation,,20,,
356,neuropils,segmentation,,21,,
357,neuropils,segmentation,,22,,
358,neuropils,segmentation,,23,,
359,neuropils,segmentation,,24,,
360,neuropils,segmentation,,25,,
361,neuropils,segmentation,,26,,
362,neuropils,segmentation,,27,,

In [ ]:
#inspect layer/ morphology cluster names
for name in sorted(all_layers_df["manual_morphology_cluster"].unique()):
    print(name)

all-synaptic
all-tissue
court et al. tracts
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary
manc-seg-v1.2 4B manual BR-1 n=6
manc-seg-v1.2 4B manual BR-2 n=10
manc-seg-v1.2 4B manual BR-3 n=4
manc-seg-v1.2 4B manual IR nomorphology assigned secondary
manc-seg-v1.2 4B manual IR-1
manc-seg-v1.2 4B manual IR-2
manc-seg-v1.2 4B manual IR-3
manc-seg-v1.2 4B manual IR-4
manc-seg-v1.2 4B manual IR-independent leg n=11
manc-seg-v1.2 4B- primary  n=4
manc-seg-v1.2 4b-manual BR-4 n=6
manc-seg-v1.2-4B-all
manc-seg-v1.2-4B-subbclass BI n=4
manc-seg-v1.2-4B-sublass IR n=60
manc-seg-v1.21- secondary n=73
manc-seg-v1.21-4B subclass BA n=1
manc-seg-v1.21-4B-subclassBR n=26
manc-seg-v1.22-4B subclass IA=4
manc-seg-v1.22-4B-early secondary n= 20
manc:v1.2.1-TTMn
nerves
neuropils

In [21]:
LAYERS_TO_ANALYZE = [
    "manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3",
    "manc-seg-v1.2 4B manual BR-1 n=6",
    "manc-seg-v1.2 4B manual BR-2 n=10",
    "manc-seg-v1.2 4B manual BR-3 n=4",
    "manc-seg-v1.2 4B manual IR-1",
    "manc-seg-v1.2 4B manual IR-2",
    "manc-seg-v1.2 4B manual IR-3",
    "manc-seg-v1.2 4B manual IR-4",
    "manc-seg-v1.2 4B manual IR-independent leg n=11",
    "manc-seg-v1.2 4b-manual BR-4 n=6",
    "manc-seg-v1.2-4B-subbclass BI n=4",
    "manc-seg-v1.2-4B-sublass IR n=60",
    "manc-seg-v1.21-4B subclass BA n=1",
    "manc-seg-v1.21-4B-subclassBR n=26",
    "manc-seg-v1.22-4B subclass IA=4",
]

selected_layers_df = (
    all_layers_df[
        all_layers_df["manual_morphology_cluster"].isin(LAYERS_TO_ANALYZE)
    ]
    .copy()
    .sort_values(["manual_morphology_cluster", "segment_id"])
    .reset_index(drop=True)
)

selected_layers_df

,manual_morphology_cluster,layer_type,visible,segment_id,manc_type,note
0,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,21862,,
1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,152655,,
2,manc-seg-v1.2 4B manual IR- proprioceptice ta...,segmentation,False,166421,,
3,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13455,,
4,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13506,,
5,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,13589,,
6,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,14728,,
7,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,14774,,
8,manc-seg-v1.2 4B manual BR-1 n=6,segmentation,False,15005,,
9,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,10024,,
10,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,12523,,
11,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,16487,,
12,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,16527,,
13,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17351,,
14,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17409,,
15,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,17534,,
16,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,18571,,
17,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,101447,,
18,manc-seg-v1.2 4B manual BR-2 n=10,segmentation,False,162540,,
19,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,15002,,
20,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,18755,,
21,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,155236,,
22,manc-seg-v1.2 4B manual BR-3 n=4,segmentation,False,164102,,
23,manc-seg-v1.2 4B manual IR-1,segmentation,True,18156,,
24,manc-seg-v1.2 4B manual IR-1,segmentation,True,18253,,
25,manc-seg-v1.2 4B manual IR-1,segmentation,True,18629,,
26,manc-seg-v1.2 4B manual IR-1,segmentation,True,19833,,
27,manc-seg-v1.2 4B manual IR-1,segmentation,True,21189,,
28,manc-seg-v1.2 4B manual IR-1,segmentation,True,21322,,
29,manc-seg-v1.2 4B manual IR-1,segmentation,True,22868,,
30,manc-seg-v1.2 4B manual IR-1,segmentation,True,23716,,
31,manc-seg-v1.2 4B manual IR-1,segmentation,True,24181,,
32,manc-seg-v1.2 4B manual IR-1,segmentation,True,26941,,
33,manc-seg-v1.2 4B manual IR-1,segmentation,True,27760,,
34,manc-seg-v1.2 4B manual IR-1,segmentation,True,38071,,
35,manc-seg-v1.2 4B manual IR-1,segmentation,True,102138,,
36,manc-seg-v1.2 4B manual IR-1,segmentation,True,102536,,
37,manc-seg-v1.2 4B manual IR-1,segmentation,True,164146,,
38,manc-seg-v1.2 4B manual IR-2,segmentation,True,18641,,
39,manc-seg-v1.2 4B manual IR-2,segmentation,True,18990,,
40,manc-seg-v1.2 4B manual IR-2,segmentation,True,21499,,
41,manc-seg-v1.2 4B manual IR-2,segmentation,True,22163,,
42,manc-seg-v1.2 4B manual IR-2,segmentation,True,22997,,
43,manc-seg-v1.2 4B manual IR-2,segmentation,True,29988,,
44,manc-seg-v1.2 4B manual IR-2,segmentation,True,100525,,
45,manc-seg-v1.2 4B manual IR-2,segmentation,True,153878,,
46,manc-seg-v1.2 4B manual IR-2,segmentation,True,165318,,
47,manc-seg-v1.2 4B manual IR-3,segmentation,True,17567,,
48,manc-seg-v1.2 4B manual IR-3,segmentation,True,17935,,
49,manc-seg-v1.2 4B manual IR-4,segmentation,True,17572,,
50,manc-seg-v1.2 4B manual IR-4,segmentation,True,18785,,
51,manc-seg-v1.2 4B manual IR-4,segmentation,True,20077,,
52,manc-seg-v1.2 4B manual IR-4,segmentation,True,21567,,
53,manc-seg-v1.2 4B manual IR-4,segmentation,True,101453,,
54,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,16224,,
55,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,20836,,
56,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,26388,,
57,manc-seg-v1.2 4B manual IR-independent leg n=11,segmentation,False,100339,,
58,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,15309,,
59,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,18148,,
60,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,19250,,
61,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,19366,,
62,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,21956,,
63,manc-seg-v1.2 4b-manual BR-4 n=6,segmentation,False,152244,,
64,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,10314,,
65,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,11143,,
66,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,13436,,
67,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,14031,,
68,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15393,,
69,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15401,,
70,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,15969,,
71,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,16293,,
72,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,17395,,
73,manc-seg-v1.2-4B-subbclass BI n=4,segmentation,False,19912,,
74,manc-seg-v1.2-4B-sublass IR n=60,segmentation,False,13409,,
75,manc-seg-v1.21-4B subclass BA n=1,segmentation,False,17490,,
76,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,15309,,
77,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,18148,,
78,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,19250,,
79,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,19366,,
80,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,21956,,
81,manc-seg-v1.21-4B-subclassBR n=26,segmentation,False,152244,,
82,manc-seg-v1.22-4B subclass IA=4,segmentation,False,10314,,
83,manc-seg-v1.22-4B subclass IA=4,segmentation,False,13436,,
84,manc-seg-v1.22-4B subclass IA=4,segmentation,False,17395,,
85,manc-seg-v1.22-4B subclass IA=4,segmentation,False,19912,,

In [23]:
# check if this ID list is compelte and does nto have duplicates

#is the same neuron added to multipel morphology clusters?
dupes = selected_layers_df[
    selected_layers_df.duplicated(subset="segment_id", keep=False)
].sort_values("segment_id")

print("Total duplicated segment IDs:", dupes["segment_id"].nunique())
dupes


#is it complete?

# ---- define the reference layer: 4B all ----
REFERENCE_LAYER = "manc-seg-v1.2-4B-all"   # replace with exact layer name from your state

# ---- get all IDs from the reference layer ----
layer_4b_all_df = (
    all_layers_df[
        all_layers_df["manual_morphology_cluster"] == REFERENCE_LAYER
    ]
    .copy()
    .sort_values("segment_id")
    .reset_index(drop=True)
)

layer_4b_all_ids = set(layer_4b_all_df["segment_id"])

# ---- get all IDs from your selected layers ----
selected_ids = set(selected_layers_df["segment_id"])

# ---- compare coverage ----
missing_from_selection = sorted(layer_4b_all_ids - selected_ids)
extra_in_selection = sorted(selected_ids - layer_4b_all_ids)

print("IDs in 4B all:", len(layer_4b_all_ids))
print("IDs in selected layers:", len(selected_ids))
print("Missing from selection:", len(missing_from_selection))
print("Extra in selection:", len(extra_in_selection))

Total duplicated segment IDs: 10
IDs in 4B all: 97
IDs in selected layers: 76
Missing from selection: 21
Extra in selection: 0

# Fix these errors when I review the updated version of MANC

In [ ]:
#----Imports
import os
import json
import pandas as pd
from pathlib import Path
#pip install neuprint-python
from neuprint import Client, fetch_neurons, fetch_custom, NeuronCriteria as NC

0.6.1

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()  # loads .env from current working directory

token = os.environ["NEUPRINT_APPLICATION_CREDENTIALS"]

In [ ]:
from neuprint import Client

c = Client(
    "https://neuprint.janelia.org",
    dataset="manc:v1.2.3",
    token=token
)
print(c)

In [7]:
from dotenv import load_dotenv
import os
from neuprint import Client

load_dotenv()
token = os.environ["NEUPRINT_APPLICATION_CREDENTIALS"]

c = Client(
    "https://neuprint.janelia.org",
    dataset="manc:v1.2.3",
    token=token
)

print(c.fetch_version())

1.7.10

In [39]:
#generate new, clean state:

new_state = {
    "title": "MANC_v1.2.3_4B_morphology_clusters_JHS",
    "layout": "3d",
    "showSlices": True,
    "projectionBackgroundColor": "#ffffff",
    "crossSectionBackgroundColor": "#808080",
    "layerListPanel": {"visible": True},
    "layers": [
        {
            "type": "image",
            "name": "EM",
            "source": em_source,
            "visible": True
        }
    ]
}

In [35]:
#populate one neuromere with 04B 

from neuprint import fetch_custom

cypher = """
MATCH (n:Neuron)
WHERE n.hemilineage = '04B'
  AND n.somaNeuromere = 'T1'
  AND n.somaSide = 'LHS'
RETURN
  n.bodyId AS bodyId,
  n.type AS type,
  n.instance AS instance,
  n.class AS class,
  n.subclass AS subclass,
  n.hemilineage AS hemilineage,
  n.somaNeuromere AS somaNeuromere,
  n.somaSide AS somaSide,
  n.rootSide AS rootSide,
  n.longTract AS longTract,
  n.birthtime AS birthtime
ORDER BY bodyId
"""

df_4b_t1_lhs = fetch_custom(cypher, client=c)
#df_4b_t1_lhs.head() 
#df_4b_t1_lhs["bodyId"].nunique() # n=97

In [41]:
# Populate: split neurons by subclass WITH colors

import json
import urllib.parse
from itertools import cycle

# --- Extract sources ---
seg_source = None
em_source = None

for L in state["layers"]:
    layer_type = L.get("type")
    src = L.get("source")

    if layer_type == "segmentation" and seg_source is None:
        url = src.get("url") if isinstance(src, dict) else src
        if "manc-seg-v1p2/manc-seg-v1.2" in str(url):
            seg_source = src

    if layer_type == "image" and em_source is None:
        em_source = src

assert seg_source is not None, "Segmentation source not found"
assert em_source is not None, "EM source not found"



# --- Color palette (cycles if needed) ---
COLORS = [
    "#87CEEB",  # sky blue
    "#FFA500",  # orange
    "#E34234",  # vermillion
    "#CC99FF",  # pale violet
    "#66CDAA",  # medium aquamarine
    "#FFD700",  # gold
]

color_cycle = cycle(COLORS)


# --- Helper with segmentColors (KEY UPGRADE) ---
def add_segmentation_layer(state, name, body_ids, seg_source, color):
    body_ids = sorted(set(int(x) for x in body_ids))
    
    state["layers"].append({
        "type": "segmentation",
        "name": name,
        "source": seg_source,
        "segments": [str(x) for x in body_ids],
        "segmentColors": {str(x): color for x in body_ids},  # <-- critical
        "visible": True,
    })


# --- Clean subclass labels ---
subclass_df = df_4b_t1_lhs.copy()
subclass_df["subclass"] = subclass_df["subclass"].fillna("unclassified").astype(str).str.strip()
subclass_df.loc[subclass_df["subclass"] == "", "subclass"] = "unclassified"


# --- Inspect counts ---
subclass_counts = (
    subclass_df.groupby("subclass")["bodyId"]
    .nunique()
    .sort_values(ascending=False)
)
print(subclass_counts)


# --- Build layers with colors ---
for subclass_name, group in subclass_df.groupby("subclass", sort=True):
    body_ids = group["bodyId"].dropna().astype(int).tolist()
    layer_name = f"MANC_v1.2.3_{subclass_name}"
    
    color = next(color_cycle)
    
    add_segmentation_layer(new_state, layer_name, body_ids, seg_source, color)


# --- Debug print ---
print("State title:", new_state["title"])
print("Number of layers:", len(new_state["layers"]))

for layer in new_state["layers"]:
    print(layer["name"], len(layer.get("segments", [])))


# --- Save ---
OUTPUT_DIR.mkdir(exist_ok=True)

STATE_OUT = OUTPUT_DIR / "MANC_v1.2.3_4B_morphology_clusters_JHS.json"

with open(STATE_OUT, "w", encoding="utf-8") as f:
    json.dump(new_state, f, indent=2)


# --- Generate Neuroglancer URL ---
encoded = urllib.parse.quote(json.dumps(new_state, separators=(",", ":")))
NEW_URL = "https://clio-ng.janelia.org/#!" + encoded

print("Saved new state:", STATE_OUT)
print("\nNew URL:\n")
print(NEW_URL)

subclass
IR    60
BR    26
BI     6
IA     4
BA     1
Name: bodyId, dtype: int64
State title: MANC_v1.2.3_4B_morphology_clusters_JHS
Number of layers: 11
EM 0
MANC_v1.2.3_BA 1
MANC_v1.2.3_BI 6
MANC_v1.2.3_BR 26
MANC_v1.2.3_IA 4
MANC_v1.2.3_IR 60
MANC_v1.2.3_BA 1
MANC_v1.2.3_BI 6
MANC_v1.2.3_BR 26
MANC_v1.2.3_IA 4
MANC_v1.2.3_IR 60
Saved new state: c:\Users\jsfdz\4B-analysis\4B-analysis\output-MANCv1.2.3_04B_morphology_clusters_T1\MANC_v1.2.3_4B_morphology_clusters_JHS.json

New URL:

https://clio-ng.janelia.org/#!%7B%22title%22%3A%22MANC_v1.2.3_4B_morphology_clusters_JHS%22%2C%22layout%22%3A%223d%22%2C%22showSlices%22%3Atrue%2C%22projectionBackgroundColor%22%3A%22%23ffffff%22%2C%22crossSectionBackgroundColor%22%3A%22%23808080%22%2C%22layerListPanel%22%3A%7B%22visible%22%3Atrue%7D%2C%22layers%22%3A%5B%7B%22type%22%3A%22image%22%2C%22name%22%3A%22EM%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//flyem-vnc-2-26-213dba213ef26e094c16c860ae7f4be0/v3_emdata_clahe_xy/jpeg%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BA%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2217490%22%5D%2C%22segmentColors%22%3A%7B%2217490%22%3A%22%2387CEEB%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BI%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2211143%22%2C%2214031%22%2C%2215393%22%2C%2215401%22%2C%2215969%22%2C%2216293%22%5D%2C%22segmentColors%22%3A%7B%2211143%22%3A%22%23FFA500%22%2C%2214031%22%3A%22%23FFA500%22%2C%2215393%22%3A%22%23FFA500%22%2C%2215401%22%3A%22%23FFA500%22%2C%2215969%22%3A%22%23FFA500%22%2C%2216293%22%3A%22%23FFA500%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BR%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2210024%22%2C%2212523%22%2C%2213455%22%2C%2213506%22%2C%2213589%22%2C%2214728%22%2C%2214774%22%2C%2215002%22%2C%2215005%22%2C%2215309%22%2C%2216487%22%2C%2216527%22%2C%2217351%22%2C%2217409%22%2C%2217534%22%2C%2218148%22%2C%2218571%22%2C%2218755%22%2C%2219250%22%2C%2219366%22%2C%2221956%22%2C%22101447%22%2C%22152244%22%2C%22155236%22%2C%22162540%22%2C%22164102%22%5D%2C%22segmentColors%22%3A%7B%2210024%22%3A%22%23E34234%22%2C%2212523%22%3A%22%23E34234%22%2C%2213455%22%3A%22%23E34234%22%2C%2213506%22%3A%22%23E34234%22%2C%2213589%22%3A%22%23E34234%22%2C%2214728%22%3A%22%23E34234%22%2C%2214774%22%3A%22%23E34234%22%2C%2215002%22%3A%22%23E34234%22%2C%2215005%22%3A%22%23E34234%22%2C%2215309%22%3A%22%23E34234%22%2C%2216487%22%3A%22%23E34234%22%2C%2216527%22%3A%22%23E34234%22%2C%2217351%22%3A%22%23E34234%22%2C%2217409%22%3A%22%23E34234%22%2C%2217534%22%3A%22%23E34234%22%2C%2218148%22%3A%22%23E34234%22%2C%2218571%22%3A%22%23E34234%22%2C%2218755%22%3A%22%23E34234%22%2C%2219250%22%3A%22%23E34234%22%2C%2219366%22%3A%22%23E34234%22%2C%2221956%22%3A%22%23E34234%22%2C%22101447%22%3A%22%23E34234%22%2C%22152244%22%3A%22%23E34234%22%2C%22155236%22%3A%22%23E34234%22%2C%22162540%22%3A%22%23E34234%22%2C%22164102%22%3A%22%23E34234%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_IA%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2210314%22%2C%2213436%22%2C%2217395%22%2C%2219912%22%5D%2C%22segmentColors%22%3A%7B%2210314%22%3A%22%23CC99FF%22%2C%2213436%22%3A%22%23CC99FF%22%2C%2217395%22%3A%22%23CC99FF%22%2C%2219912%22%3A%22%23CC99FF%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_IR%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2213128%22%2C%2213409%22%2C%2213770%22%2C%2213798%22%2C%2213975%22%2C%2214024%22%2C%2214389%22%2C%2214697%22%2C%2214954%22%2C%2215811%22%2C%2216224%22%2C%2216757%22%2C%2217567%22%2C%2217572%22%2C%2217678%22%2C%2217935%22%2C%2218156%22%2C%2218253%22%2C%2218605%22%2C%2218629%22%2C%2218641%22%2C%2218724%22%2C%2218785%22%2C%2218831%22%2C%2218990%22%2C%2219833%22%2C%2219985%22%2C%2220077%22%2C%2220585%22%2C%2220836%22%2C%2220932%22%2C%2221189%22%2C%2221322%22%2C%2221499%22%2C%2221567%22%2C%2221808%22%2C%2221862%22%2C%2222163%22%2C%2222868%22%2C%2222997%22%2C%2223716%22%2C%2223790%22%2C%2224181%22%2C%2226388%22%2C%2226941%22%2C%2227760%22%2C%2229988%22%2C%2236722%22%2C%2238071%22%2C%22100339%22%2C%22100525%22%2C%22101453%22%2C%22102138%22%2C%22102536%22%2C%22152655%22%2C%22153878%22%2C%22158391%22%2C%22164146%22%2C%22165318%22%2C%22166421%22%5D%2C%22segmentColors%22%3A%7B%2213128%22%3A%22%2366CDAA%22%2C%2213409%22%3A%22%2366CDAA%22%2C%2213770%22%3A%22%2366CDAA%22%2C%2213798%22%3A%22%2366CDAA%22%2C%2213975%22%3A%22%2366CDAA%22%2C%2214024%22%3A%22%2366CDAA%22%2C%2214389%22%3A%22%2366CDAA%22%2C%2214697%22%3A%22%2366CDAA%22%2C%2214954%22%3A%22%2366CDAA%22%2C%2215811%22%3A%22%2366CDAA%22%2C%2216224%22%3A%22%2366CDAA%22%2C%2216757%22%3A%22%2366CDAA%22%2C%2217567%22%3A%22%2366CDAA%22%2C%2217572%22%3A%22%2366CDAA%22%2C%2217678%22%3A%22%2366CDAA%22%2C%2217935%22%3A%22%2366CDAA%22%2C%2218156%22%3A%22%2366CDAA%22%2C%2218253%22%3A%22%2366CDAA%22%2C%2218605%22%3A%22%2366CDAA%22%2C%2218629%22%3A%22%2366CDAA%22%2C%2218641%22%3A%22%2366CDAA%22%2C%2218724%22%3A%22%2366CDAA%22%2C%2218785%22%3A%22%2366CDAA%22%2C%2218831%22%3A%22%2366CDAA%22%2C%2218990%22%3A%22%2366CDAA%22%2C%2219833%22%3A%22%2366CDAA%22%2C%2219985%22%3A%22%2366CDAA%22%2C%2220077%22%3A%22%2366CDAA%22%2C%2220585%22%3A%22%2366CDAA%22%2C%2220836%22%3A%22%2366CDAA%22%2C%2220932%22%3A%22%2366CDAA%22%2C%2221189%22%3A%22%2366CDAA%22%2C%2221322%22%3A%22%2366CDAA%22%2C%2221499%22%3A%22%2366CDAA%22%2C%2221567%22%3A%22%2366CDAA%22%2C%2221808%22%3A%22%2366CDAA%22%2C%2221862%22%3A%22%2366CDAA%22%2C%2222163%22%3A%22%2366CDAA%22%2C%2222868%22%3A%22%2366CDAA%22%2C%2222997%22%3A%22%2366CDAA%22%2C%2223716%22%3A%22%2366CDAA%22%2C%2223790%22%3A%22%2366CDAA%22%2C%2224181%22%3A%22%2366CDAA%22%2C%2226388%22%3A%22%2366CDAA%22%2C%2226941%22%3A%22%2366CDAA%22%2C%2227760%22%3A%22%2366CDAA%22%2C%2229988%22%3A%22%2366CDAA%22%2C%2236722%22%3A%22%2366CDAA%22%2C%2238071%22%3A%22%2366CDAA%22%2C%22100339%22%3A%22%2366CDAA%22%2C%22100525%22%3A%22%2366CDAA%22%2C%22101453%22%3A%22%2366CDAA%22%2C%22102138%22%3A%22%2366CDAA%22%2C%22102536%22%3A%22%2366CDAA%22%2C%22152655%22%3A%22%2366CDAA%22%2C%22153878%22%3A%22%2366CDAA%22%2C%22158391%22%3A%22%2366CDAA%22%2C%22164146%22%3A%22%2366CDAA%22%2C%22165318%22%3A%22%2366CDAA%22%2C%22166421%22%3A%22%2366CDAA%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BA%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2217490%22%5D%2C%22segmentColors%22%3A%7B%2217490%22%3A%22%2387CEEB%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BI%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2211143%22%2C%2214031%22%2C%2215393%22%2C%2215401%22%2C%2215969%22%2C%2216293%22%5D%2C%22segmentColors%22%3A%7B%2211143%22%3A%22%23FFA500%22%2C%2214031%22%3A%22%23FFA500%22%2C%2215393%22%3A%22%23FFA500%22%2C%2215401%22%3A%22%23FFA500%22%2C%2215969%22%3A%22%23FFA500%22%2C%2216293%22%3A%22%23FFA500%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_BR%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2210024%22%2C%2212523%22%2C%2213455%22%2C%2213506%22%2C%2213589%22%2C%2214728%22%2C%2214774%22%2C%2215002%22%2C%2215005%22%2C%2215309%22%2C%2216487%22%2C%2216527%22%2C%2217351%22%2C%2217409%22%2C%2217534%22%2C%2218148%22%2C%2218571%22%2C%2218755%22%2C%2219250%22%2C%2219366%22%2C%2221956%22%2C%22101447%22%2C%22152244%22%2C%22155236%22%2C%22162540%22%2C%22164102%22%5D%2C%22segmentColors%22%3A%7B%2210024%22%3A%22%23E34234%22%2C%2212523%22%3A%22%23E34234%22%2C%2213455%22%3A%22%23E34234%22%2C%2213506%22%3A%22%23E34234%22%2C%2213589%22%3A%22%23E34234%22%2C%2214728%22%3A%22%23E34234%22%2C%2214774%22%3A%22%23E34234%22%2C%2215002%22%3A%22%23E34234%22%2C%2215005%22%3A%22%23E34234%22%2C%2215309%22%3A%22%23E34234%22%2C%2216487%22%3A%22%23E34234%22%2C%2216527%22%3A%22%23E34234%22%2C%2217351%22%3A%22%23E34234%22%2C%2217409%22%3A%22%23E34234%22%2C%2217534%22%3A%22%23E34234%22%2C%2218148%22%3A%22%23E34234%22%2C%2218571%22%3A%22%23E34234%22%2C%2218755%22%3A%22%23E34234%22%2C%2219250%22%3A%22%23E34234%22%2C%2219366%22%3A%22%23E34234%22%2C%2221956%22%3A%22%23E34234%22%2C%22101447%22%3A%22%23E34234%22%2C%22152244%22%3A%22%23E34234%22%2C%22155236%22%3A%22%23E34234%22%2C%22162540%22%3A%22%23E34234%22%2C%22164102%22%3A%22%23E34234%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_IA%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2210314%22%2C%2213436%22%2C%2217395%22%2C%2219912%22%5D%2C%22segmentColors%22%3A%7B%2210314%22%3A%22%23CC99FF%22%2C%2213436%22%3A%22%23CC99FF%22%2C%2217395%22%3A%22%23CC99FF%22%2C%2219912%22%3A%22%23CC99FF%22%7D%2C%22visible%22%3Atrue%7D%2C%7B%22type%22%3A%22segmentation%22%2C%22name%22%3A%22MANC_v1.2.3_IR%22%2C%22source%22%3A%7B%22url%22%3A%22precomputed%3A//gs%3A//manc-seg-v1p2/manc-seg-v1.2%22%2C%22subsources%22%3A%7B%22default%22%3Atrue%2C%22properties%22%3Atrue%2C%22mesh%22%3Atrue%7D%2C%22enableDefaultSubsources%22%3Afalse%7D%2C%22segments%22%3A%5B%2213128%22%2C%2213409%22%2C%2213770%22%2C%2213798%22%2C%2213975%22%2C%2214024%22%2C%2214389%22%2C%2214697%22%2C%2214954%22%2C%2215811%22%2C%2216224%22%2C%2216757%22%2C%2217567%22%2C%2217572%22%2C%2217678%22%2C%2217935%22%2C%2218156%22%2C%2218253%22%2C%2218605%22%2C%2218629%22%2C%2218641%22%2C%2218724%22%2C%2218785%22%2C%2218831%22%2C%2218990%22%2C%2219833%22%2C%2219985%22%2C%2220077%22%2C%2220585%22%2C%2220836%22%2C%2220932%22%2C%2221189%22%2C%2221322%22%2C%2221499%22%2C%2221567%22%2C%2221808%22%2C%2221862%22%2C%2222163%22%2C%2222868%22%2C%2222997%22%2C%2223716%22%2C%2223790%22%2C%2224181%22%2C%2226388%22%2C%2226941%22%2C%2227760%22%2C%2229988%22%2C%2236722%22%2C%2238071%22%2C%22100339%22%2C%22100525%22%2C%22101453%22%2C%22102138%22%2C%22102536%22%2C%22152655%22%2C%22153878%22%2C%22158391%22%2C%22164146%22%2C%22165318%22%2C%22166421%22%5D%2C%22segmentColors%22%3A%7B%2213128%22%3A%22%2366CDAA%22%2C%2213409%22%3A%22%2366CDAA%22%2C%2213770%22%3A%22%2366CDAA%22%2C%2213798%22%3A%22%2366CDAA%22%2C%2213975%22%3A%22%2366CDAA%22%2C%2214024%22%3A%22%2366CDAA%22%2C%2214389%22%3A%22%2366CDAA%22%2C%2214697%22%3A%22%2366CDAA%22%2C%2214954%22%3A%22%2366CDAA%22%2C%2215811%22%3A%22%2366CDAA%22%2C%2216224%22%3A%22%2366CDAA%22%2C%2216757%22%3A%22%2366CDAA%22%2C%2217567%22%3A%22%2366CDAA%22%2C%2217572%22%3A%22%2366CDAA%22%2C%2217678%22%3A%22%2366CDAA%22%2C%2217935%22%3A%22%2366CDAA%22%2C%2218156%22%3A%22%2366CDAA%22%2C%2218253%22%3A%22%2366CDAA%22%2C%2218605%22%3A%22%2366CDAA%22%2C%2218629%22%3A%22%2366CDAA%22%2C%2218641%22%3A%22%2366CDAA%22%2C%2218724%22%3A%22%2366CDAA%22%2C%2218785%22%3A%22%2366CDAA%22%2C%2218831%22%3A%22%2366CDAA%22%2C%2218990%22%3A%22%2366CDAA%22%2C%2219833%22%3A%22%2366CDAA%22%2C%2219985%22%3A%22%2366CDAA%22%2C%2220077%22%3A%22%2366CDAA%22%2C%2220585%22%3A%22%2366CDAA%22%2C%2220836%22%3A%22%2366CDAA%22%2C%2220932%22%3A%22%2366CDAA%22%2C%2221189%22%3A%22%2366CDAA%22%2C%2221322%22%3A%22%2366CDAA%22%2C%2221499%22%3A%22%2366CDAA%22%2C%2221567%22%3A%22%2366CDAA%22%2C%2221808%22%3A%22%2366CDAA%22%2C%2221862%22%3A%22%2366CDAA%22%2C%2222163%22%3A%22%2366CDAA%22%2C%2222868%22%3A%22%2366CDAA%22%2C%2222997%22%3A%22%2366CDAA%22%2C%2223716%22%3A%22%2366CDAA%22%2C%2223790%22%3A%22%2366CDAA%22%2C%2224181%22%3A%22%2366CDAA%22%2C%2226388%22%3A%22%2366CDAA%22%2C%2226941%22%3A%22%2366CDAA%22%2C%2227760%22%3A%22%2366CDAA%22%2C%2229988%22%3A%22%2366CDAA%22%2C%2236722%22%3A%22%2366CDAA%22%2C%2238071%22%3A%22%2366CDAA%22%2C%22100339%22%3A%22%2366CDAA%22%2C%22100525%22%3A%22%2366CDAA%22%2C%22101453%22%3A%22%2366CDAA%22%2C%22102138%22%3A%22%2366CDAA%22%2C%22102536%22%3A%22%2366CDAA%22%2C%22152655%22%3A%22%2366CDAA%22%2C%22153878%22%3A%22%2366CDAA%22%2C%22158391%22%3A%22%2366CDAA%22%2C%22164146%22%3A%22%2366CDAA%22%2C%22165318%22%3A%22%2366CDAA%22%2C%22166421%22%3A%22%2366CDAA%22%7D%2C%22visible%22%3Atrue%7D%5D%7D