MANC notebook- create csv annotation fils accompanying neuroglancer links from MANC version v1.2. Jelly Soffers 20260309

In [1]:
# set up environment
import sys
import json
import re
import requests
import pandas as pd
from pathlib import Path
import json

from caveclient import CAVEclient

print("Python executable:", sys.executable)
print("Imports OK")

c:\Users\JHS\Documents\Python\cave_env\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

Python executable: c:\Users\JHS\Documents\Python\cave_env\Scripts\python.exe
Imports OK

In [2]:
PROJECT_ROOT = Path.cwd()

# input from previous script
INPUT_DIR = PROJECT_ROOT / "output"
INPUT_DIR.mkdir(exist_ok=True)

# output for THIS notebook
OUTPUT_DIR = PROJECT_ROOT / "output-MN"
OUTPUT_DIR.mkdir(exist_ok=True)

print("Input:", INPUT_DIR)
print("Output:", OUTPUT_DIR)

# select startign neuroglancer state: 
STATE_IN = INPUT_DIR / "manc_v1p2_with_manual_IR_layers.json"

with open(STATE_IN, "r", encoding="utf-8") as f:
    state = json.load(f)

#define the name of the modified link and where the state will be stored 
STATE_OUT = OUTPUT_DIR / "manc_v1p2_IR_to_MN.json"

with open(STATE_OUT, "w", encoding="utf-8") as f:
    json.dump(state, f, indent=2)

Input: c:\Users\JHS\Documents\Python\project_folder_4B\output
Output: c:\Users\JHS\Documents\Python\project_folder_4B\output-MN

# Part 1: select layers and make a dictionary that contains the bodyIDs per layer

In [ ]:
#Build one master DataFrame with one row per body ID
rows = []

for L in state.get("layers", []):
    layer_name = L.get("name", "")
    layer_type = L.get("type", "")
    visible = L.get("visible", "")
    body_ids = L.get("segments", []) or []

    if layer_type != "segmentation":
        continue
    if not body_ids:
        continue

    for b in body_ids:
        rows.append({
            "layer_name": layer_name,
            "layer_type": layer_type,
            "visible": visible,
            "bodyId": int(b)
        })

all_layers_df = (
    pd.DataFrame(rows)
    .drop_duplicates()
    .sort_values(["layer_name", "bodyId"])
    .reset_index(drop=True)
)

#all_layers_df.head()
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

all_layers_df


#build dictionary that contains the body IDs per layer
layer_bodyids = (
    all_layers_df
    .groupby("layer_name")["bodyId"]
    .apply(list)
    .to_dict()
)

layer_bodyids 


#select the layers to analyze 
sorted(all_layers_df["layer_name"].unique())

for name in sorted(all_layers_df["layer_name"].unique()):
    print(name)

##set selection:
LAYERS_TO_ANALYZE = [
    "manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3",
    "manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary",
    "manc-seg-v1.2 4B manual IR-1",
    "manc-seg-v1.2 4B manual IR-2",
    "manc-seg-v1.2 4B manual IR-3",
    "manc-seg-v1.2 4B manual IR-4",
    "manc-seg-v1.2 4B manual IR-independent leg n=11",
]

# make df of layers to analize:
selected_layers_df = all_layers_df[
    all_layers_df["layer_name"].isin(LAYERS_TO_ANALYZE)
].copy()

selected_layers_df = selected_layers_df.sort_values(
    ["layer_name", "bodyId"]
).reset_index(drop=True)


#check if there are duplicate bodyIDs in this selection:
dupes = selected_layers_df[
    selected_layers_df.duplicated(subset="bodyId", keep=False)
].sort_values("bodyId")

dupes

##in selected layer df, inspect IDs per layer; 
#selected_layers_df[
   # selected_layers_df["layer_name"] == "manc-seg-v1.2 4B manual IR-1"
#]

#ids = selected_layers_df.loc[
 #   selected_layers_df["layer_name"] == "manc-seg-v1.2 4B manual IR-1",
  #  "bodyId"
#].tolist()

#make a dictionary for bodyIDs per layer for my selection:
selected_layer_bodyids_dict = (
    selected_layers_df
    .groupby("layer_name")["bodyId"]
    .apply(list)
    .to_dict()
)

all-synaptic
all-tissue
court et al. tracts
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary
manc-seg-v1.2 4B manual BR-1 n=6
manc-seg-v1.2 4B manual BR-2 n=10
manc-seg-v1.2 4B manual BR-3 n=4
manc-seg-v1.2 4B manual IR nomorphology assigned secondary
manc-seg-v1.2 4B manual IR-1
manc-seg-v1.2 4B manual IR-2
manc-seg-v1.2 4B manual IR-3
manc-seg-v1.2 4B manual IR-4
manc-seg-v1.2 4B manual IR-independent leg n=11
manc-seg-v1.2 4B- primary  n=4
manc-seg-v1.2 4b-manual BR-4 n=6
manc-seg-v1.2-4B-all
manc-seg-v1.2-4B-subbclass BI n=4
manc-seg-v1.2-4B-sublass IR n=60
manc-seg-v1.21- secondary n=73
manc-seg-v1.21-4B subclass BA n=1
manc-seg-v1.21-4B-subclassBR n=26
manc-seg-v1.22-4B subclass IA=4
manc-seg-v1.22-4B-early secondary n= 20
manc:v1.2.1-TTMn
nerves
neuropils
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3 3
n all layers: 27
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary 7
n all layers: 27
manc-seg-v1.2 4B manual IR-1 15
n all layers: 27
manc-seg-v1.2 4B manual IR-2 9
n all layers: 27
manc-seg-v1.2 4B manual IR-3 2
n all layers: 27
manc-seg-v1.2 4B manual IR-4 5
n all layers: 27
manc-seg-v1.2 4B manual IR-independent leg n=11 4
n all layers: 27
n selected layers: 7

Selected unique layer names:
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3

Dict keys:
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary

Dict keys:
manc-seg-v1.2 4B manual IR-1

Dict keys:
manc-seg-v1.2 4B manual IR-2

Dict keys:
manc-seg-v1.2 4B manual IR-3

Dict keys:
manc-seg-v1.2 4B manual IR-4

Dict keys:
manc-seg-v1.2 4B manual IR-independent leg n=11

Dict keys:
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary
manc-seg-v1.2 4B manual IR-1
manc-seg-v1.2 4B manual IR-2
manc-seg-v1.2 4B manual IR-3
manc-seg-v1.2 4B manual IR-4
manc-seg-v1.2 4B manual IR-independent leg n=11

In [ ]:

# #print IDs fper layer of interest:
# for layer_name, body_ids in selected_layer_bodyids_dict.items():
#     print(layer_name, len(body_ids))

#     print("n all layers:", all_layers_df["layer_name"].nunique())
# print("n selected layers:", selected_layers_df["layer_name"].nunique())

# print("\nSelected unique layer names:")
# for x in sorted(selected_layers_df["layer_name"].unique()):
#     print(x)

#     print("\nDict keys:")
# for x in sorted(selected_layer_bodyids_dict.keys()):
#     print(x)

manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3 3
n all layers: 27
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary 7
n all layers: 27
manc-seg-v1.2 4B manual IR-1 15
n all layers: 27
manc-seg-v1.2 4B manual IR-2 9
n all layers: 27
manc-seg-v1.2 4B manual IR-3 2
n all layers: 27
manc-seg-v1.2 4B manual IR-4 5
n all layers: 27
manc-seg-v1.2 4B manual IR-independent leg n=11 4
n all layers: 27
n selected layers: 7

Selected unique layer names:
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3

Dict keys:
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary

Dict keys:
manc-seg-v1.2 4B manual IR-1

Dict keys:
manc-seg-v1.2 4B manual IR-2

Dict keys:
manc-seg-v1.2 4B manual IR-3

Dict keys:
manc-seg-v1.2 4B manual IR-4

Dict keys:
manc-seg-v1.2 4B manual IR-independent leg n=11

Dict keys:
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary
manc-seg-v1.2 4B manual IR-1
manc-seg-v1.2 4B manual IR-2
manc-seg-v1.2 4B manual IR-3
manc-seg-v1.2 4B manual IR-4
manc-seg-v1.2 4B manual IR-independent leg n=11

# Part II
now we are ready for a neupritn query to find synaptic partners for each ID and then filter out which of those are Mns

In [ ]:
#!pip install neuprint-python 

from neuprint import Client

NEUPRINT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imouc29mZmVyc0BnbWFpbC5jb20iLCJsZXZlbCI6Im5vYXV0aCIsImltYWdlLXVybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tRb1JBeUdrdjJmNF9UUU1LOTBIMEk4Nm5xLXN4eE04ZXhCMzEwYlFPaEdSdGNiQT1zOTYtYz9zej01MD9zej01MCIsImV4cCI6MTk1NTA1MTE0OH0.9Z-exWUI72AE2xR4p8Mpo21PPAO3ZtXoYSCdPV10MR0"

c = Client(
    "neuprint.janelia.org",
    dataset="manc:v1.2.1",
    token=NEUPRINT_TOKEN
)

print("Connected to MANC")

Requirement already satisfied: neuprint-python in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (0.6.1)
Requirement already satisfied: requests>=2.22 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (2.32.5)
Requirement already satisfied: pandas in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (2.3.3)
Requirement already satisfied: tqdm in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (4.67.3)
Requirement already satisfied: ujson in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (5.12.0)
Requirement already satisfied: asciitree in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (0.3.3)
Requirement already satisfied: scipy in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (1.17.1)
Requirement already satisfied: networkx in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (3.6.1)
Requirement already satisfied: packaging in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (26.0)
Requirement already satisfied: pyarrow in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from neuprint-python) (23.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from requests>=2.22->neuprint-python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from requests>=2.22->neuprint-python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from requests>=2.22->neuprint-python) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from requests>=2.22->neuprint-python) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from pandas->neuprint-python) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from pandas->neuprint-python) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from pandas->neuprint-python) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from pandas->neuprint-python) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->neuprint-python) (1.17.0)
Requirement already satisfied: colorama in C:\Users\JHS\Documents\Python\cave_env\Lib\site-packages (from tqdm->neuprint-python) (0.4.6)
Connected to MANC

#for IDs in layer find partners. Filder MN, then fidn Mn per id (faster computing)

In [10]:
from neuprint import fetch_adjacencies
import pandas as pd

all_neuron_tables = []
all_conn_tables = []

for layer_name, source_ids in selected_layer_bodyids_dict.items():
    print(f"Querying {layer_name} with {len(source_ids)} source IDs")

    if not source_ids:
        continue

    neuron_df, conn_df = fetch_adjacencies(
        sources=source_ids,
        targets=None,
        client=c
    )

    if neuron_df is not None and not neuron_df.empty:
        neuron_df = neuron_df.copy()
        neuron_df["layer_name"] = layer_name
        all_neuron_tables.append(neuron_df)

    if conn_df is not None and not conn_df.empty:
        conn_df = conn_df.copy()
        conn_df["layer_name"] = layer_name
        all_conn_tables.append(conn_df)

all_neurons_df = (
    pd.concat(all_neuron_tables, ignore_index=True)
    if all_neuron_tables else pd.DataFrame()
)

all_edges_df = (
    pd.concat(all_conn_tables, ignore_index=True)
    if all_conn_tables else pd.DataFrame()
)

print("Done.")
print("Rows in all_neurons_df:", len(all_neurons_df))
print("Rows in all_edges_df:", len(all_edges_df))

Querying manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3 with 3 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary with 7 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual IR-1 with 15 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual IR-2 with 9 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual IR-3 with 2 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual IR-4 with 5 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Querying manc-seg-v1.2 4B manual IR-independent leg n=11 with 4 source IDs

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Done.
Rows in all_neurons_df: 5838
Rows in all_edges_df: 10697

In [ ]:
# print(all_neurons_df.columns.tolist())
# print(all_edges_df.columns.tolist())
# all_edges_df.head()

['bodyId', 'type', 'instance', 'layer_name']
['bodyId_pre', 'bodyId_post', 'roi', 'weight', 'layer_name']

,bodyId_pre,bodyId_post,roi,weight,layer_name
0,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...
1,21862,10114,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...
2,21862,10126,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...
3,21862,10185,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...
4,21862,10192,LegNp(T1)(L),66,manc-seg-v1.2 4B manual IR- proprioceptice ta...

In [12]:
#subset by synaptic weight if desired:
if "weight" in all_edges_df.columns:
    all_edges_df = all_edges_df[all_edges_df["weight"] >= 1].copy()

print("Rows after weight filter:", len(all_edges_df))

Rows after weight filter: 10697

#From all downstream synaptic partners, filter out the ones that are Mns

In [13]:
from neuprint import merge_neuron_properties

# add type/instance metadata for pre and post neurons
all_edges_annot_df = merge_neuron_properties(
    all_neurons_df,
    all_edges_df,
    properties=["type", "instance"]
)

print(all_edges_annot_df.columns.tolist())
all_edges_annot_df.head()

['bodyId_pre', 'bodyId_post', 'roi', 'weight', 'layer_name', 'type_pre', 'instance_pre', 'type_post', 'instance_post']

,bodyId_pre,bodyId_post,roi,weight,layer_name,type_pre,instance_pre,type_post,instance_post
0,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,IN04B101,IN04B101_T1_L,IN08B001,IN08B001_T1_R
1,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,IN04B101,IN04B101_T1_L,IN08B001,IN08B001_T1_R
2,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,IN04B101,IN04B101_T1_L,IN08B001,IN08B001_T1_R
3,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,IN04B101,IN04B101_T1_L,IN08B001,IN08B001_T1_R
4,21862,10091,LegNp(T1)(L),1,manc-seg-v1.2 4B manual IR- proprioceptice ta...,IN04B101,IN04B101_T1_L,IN08B001,IN08B001_T1_R

In [14]:
mn_edges_df = all_edges_annot_df[
    all_edges_annot_df["type_post"].fillna("").str.contains("motor", case=False)
    | all_edges_annot_df["instance_post"].fillna("").str.contains("motor", case=False)
].copy()

print("Edges to downstream MNs:", len(mn_edges_df))
mn_edges_df[["layer_name", "bodyId_pre", "bodyId_post", "type_post", "instance_post", "weight"]].head(20)

Edges to downstream MNs: 3974

,layer_name,bodyId_pre,bodyId_post,type_post,instance_post,weight
1320,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1321,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1322,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1323,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1324,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1325,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1326,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1327,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1328,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1329,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1330,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1331,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1332,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1333,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1334,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1335,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1336,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1337,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1338,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20
1339,manc-seg-v1.2 4B manual IR- proprioceptice ta...,21862,12396,Tergopleural/Pleural promotor MN,MNfl56_DProN_L,20

In [18]:
# Store source IDs in each layer that talk to MNs
mn_source_summary_df = (
    mn_edges_df
    .groupby(["layer_name", "bodyId_pre"])["bodyId_post"]
    .nunique()
    .reset_index(name="n_downstream_MNs")
    .rename(columns={"bodyId_pre": "bodyId"})
)

mn_source_summary_df["talks_to_downstream_MN"] = True
mn_source_summary_df.head()


#merge back

selected_layers_with_mn_df = selected_layers_df.merge(
    mn_source_summary_df,
    on=["layer_name", "bodyId"],
    how="left"
)

selected_layers_with_mn_df["n_downstream_MNs"] = (
    selected_layers_with_mn_df["n_downstream_MNs"].fillna(0).astype(int)
)
selected_layers_with_mn_df["talks_to_downstream_MN"] = (
    selected_layers_with_mn_df["talks_to_downstream_MN"].fillna(False)
)

selected_layers_with_mn_df.head()

#save 
mn_edges_df.to_csv(OUTPUT_DIR / "selected_layers_downstream_MN_edges.csv", index=False)
selected_layers_with_mn_df.to_csv(OUTPUT_DIR / "selected_layers_bodyIds_with_MN_flags.csv", index=False)

C:\Users\JHS\AppData\Local\Temp\ipykernel_13680\94512845.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  selected_layers_with_mn_df["talks_to_downstream_MN"].fillna(False)

In [ ]:
# print("=== Number of neurons per layer that talk to MNs ===")
# print(selected_layers_with_mn_df.groupby("layer_name")["talks_to_downstream_MN"].sum())

# print("\n=== Fraction of neurons per layer that talk to MNs ===")
# print(selected_layers_with_mn_df.groupby("layer_name")["talks_to_downstream_MN"].mean())

# print("\n=== Top downstream MN targets ===")
# print(mn_edges_df["bodyId_post"].value_counts().head(10))

# print("\n=== Example MN edges ===")
# print(
#     mn_edges_df.sample(10)[
#         ["layer_name", "bodyId_pre", "bodyId_post", "type_post", "weight"]
#     ]
# )

=== Number of neurons per layer that talk to MNs ===
layer_name
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3               3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary     5
manc-seg-v1.2 4B manual IR-1                                         13
manc-seg-v1.2 4B manual IR-2                                          7
manc-seg-v1.2 4B manual IR-3                                          1
manc-seg-v1.2 4B manual IR-4                                          5
manc-seg-v1.2 4B manual IR-independent leg n=11                       2
Name: talks_to_downstream_MN, dtype: int64

=== Fraction of neurons per layer that talk to MNs ===
layer_name
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3              1.000000
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary    0.714286
manc-seg-v1.2 4B manual IR-1                                         0.866667
manc-seg-v1.2 4B manual IR-2                                         0.777778
manc-seg-v1.2 4B manual IR-3                                         0.500000
manc-seg-v1.2 4B manual IR-4                                         1.000000
manc-seg-v1.2 4B manual IR-independent leg n=11                      0.500000
Name: talks_to_downstream_MN, dtype: float64

=== Top downstream MN targets ===
bodyId_post
13490    931
12686    847
19319    812
12396    679
12096    430
13628    275
Name: count, dtype: int64

=== Example MN edges ===
                                               layer_name  bodyId_pre  \
18027   manc-seg-v1.2 4B manual  IR-nomorphology assig...       17572
56586   manc-seg-v1.2 4B manual  IR-nomorphology assig...      101453
1331    manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1410    manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
92133                        manc-seg-v1.2 4B manual IR-1       24181
17743   manc-seg-v1.2 4B manual  IR-nomorphology assig...       17572
144478                       manc-seg-v1.2 4B manual IR-2       29988
8376    manc-seg-v1.2 4B manual  IR- proprioceptice ta...      166421
168719                       manc-seg-v1.2 4B manual IR-3       17935
122289                       manc-seg-v1.2 4B manual IR-2       18641

        bodyId_post                         type_post  weight
18027         12396  Tergopleural/Pleural promotor MN       4
56586         13490  Tergopleural/Pleural promotor MN       2
1331          12396  Tergopleural/Pleural promotor MN      20
1410          12686  Tergopleural/Pleural promotor MN      38
92133         12396  Tergopleural/Pleural promotor MN       2
17743         12096       Pleural remotor/abductor MN       2
144478        12396  Tergopleural/Pleural promotor MN       2
8376          13490  Tergopleural/Pleural promotor MN      20
168719        12686  Tergopleural/Pleural promotor MN      37
122289        19319  Tergopleural/Pleural promotor MN       3

In [21]:
print("\n" + "="*60)
print("SUMMARY OF DOWNSTREAM MOTOR NEURON ANALYSIS")
print("="*60)

# 1. number of neurons per layer that talk to MNs
print("\nNeurons per layer that talk to downstream MNs:")
print(selected_layers_with_mn_df.groupby("layer_name")["talks_to_downstream_MN"].sum())

# 2. fraction per layer that talk to MNs
print("\nFraction of neurons per layer that talk to downstream MNs:")
print(selected_layers_with_mn_df.groupby("layer_name")["talks_to_downstream_MN"].mean())

# 3. all unique MN targets
mn_targets = sorted(mn_edges_df["bodyId_post"].unique())
print("\nAll unique downstream MN targets:")
print(mn_targets)
print("\nNumber of unique MN targets:", len(mn_targets))

# 4. top MN targets by number of incoming edges from your selected neurons
print("\nTop downstream MN targets by edge count:")
print(mn_edges_df["bodyId_post"].value_counts())

# 5. example edges
print("\nExample MN edges:")
print(
    mn_edges_df[["layer_name", "bodyId_pre", "bodyId_post", "type_post", "weight"]]
    .sort_values(["layer_name", "bodyId_pre", "weight"], ascending=[True, True, False])
    .head(20)
)

============================================================
SUMMARY OF DOWNSTREAM MOTOR NEURON ANALYSIS
============================================================

Neurons per layer that talk to downstream MNs:
layer_name
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3               3
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary     5
manc-seg-v1.2 4B manual IR-1                                         13
manc-seg-v1.2 4B manual IR-2                                          7
manc-seg-v1.2 4B manual IR-3                                          1
manc-seg-v1.2 4B manual IR-4                                          5
manc-seg-v1.2 4B manual IR-independent leg n=11                       2
Name: talks_to_downstream_MN, dtype: int64

Fraction of neurons per layer that talk to downstream MNs:
layer_name
manc-seg-v1.2 4B manual  IR- proprioceptice tactile n=3              1.000000
manc-seg-v1.2 4B manual  IR-nomorphology assigned-early secondary    0.714286
manc-seg-v1.2 4B manual IR-1                                         0.866667
manc-seg-v1.2 4B manual IR-2                                         0.777778
manc-seg-v1.2 4B manual IR-3                                         0.500000
manc-seg-v1.2 4B manual IR-4                                         1.000000
manc-seg-v1.2 4B manual IR-independent leg n=11                      0.500000
Name: talks_to_downstream_MN, dtype: float64

All unique downstream MN targets:
[np.int64(12096), np.int64(12396), np.int64(12686), np.int64(13490), np.int64(13628), np.int64(19319)]

Number of unique MN targets: 6

Top downstream MN targets by edge count:
bodyId_post
13490    931
12686    847
19319    812
12396    679
12096    430
13628    275
Name: count, dtype: int64

Example MN edges:
                                             layer_name  bodyId_pre  \
1404  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1405  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1406  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1407  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1408  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1409  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1410  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1411  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1412  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1413  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1414  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1415  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1416  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1417  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1418  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1419  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1420  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1421  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1422  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862
1423  manc-seg-v1.2 4B manual  IR- proprioceptice ta...       21862

      bodyId_post                         type_post  weight
1404        12686  Tergopleural/Pleural promotor MN      38
1405        12686  Tergopleural/Pleural promotor MN      38
1406        12686  Tergopleural/Pleural promotor MN      38
1407        12686  Tergopleural/Pleural promotor MN      38
1408        12686  Tergopleural/Pleural promotor MN      38
1409        12686  Tergopleural/Pleural promotor MN      38
1410        12686  Tergopleural/Pleural promotor MN      38
1411        12686  Tergopleural/Pleural promotor MN      38
1412        12686  Tergopleural/Pleural promotor MN      38
1413        12686  Tergopleural/Pleural promotor MN      38
1414        12686  Tergopleural/Pleural promotor MN      38
1415        12686  Tergopleural/Pleural promotor MN      38
1416        12686  Tergopleural/Pleural promotor MN      38
1417        12686  Tergopleural/Pleural promotor MN      38
1418        12686  Tergopleural/Pleural promotor MN      38
1419        12686  Tergopleural/Pleural promotor MN      38
1420        12686  Tergopleural/Pleural promotor MN      38
1421        12686  Tergopleural/Pleural promotor MN      38
1422        12686  Tergopleural/Pleural promotor MN      38
1423        12686  Tergopleural/Pleural promotor MN      38

In [22]:
mn_targets_df = (
    mn_edges_df[["bodyId_post", "type_post", "instance_post"]]
    .drop_duplicates()
    .sort_values("bodyId_post")
    .reset_index(drop=True)
)

print("\nUnique downstream MN targets with annotations:")
print(mn_targets_df)

Unique downstream MN targets with annotations:
   bodyId_post                         type_post   instance_post
0        12096       Pleural remotor/abductor MN  MNfl31_ProAN_L
1        12396  Tergopleural/Pleural promotor MN  MNfl56_DProN_L
2        12686  Tergopleural/Pleural promotor MN  MNfl54_DProN_L
3        13490  Tergopleural/Pleural promotor MN  MNfl53_DProN_L
4        13628       Pleural remotor/abductor MN  MNfl17_ProAN_L
5        19319  Tergopleural/Pleural promotor MN  MNfl55_DProN_L

In [ ]:
#part III: make a neyurclancer link that shwos the Mns that partner, and that are grouped  in layers for each 4B morphological layer

In [31]:
# build MN targets per layer
mn_targets_per_layer_dict = (
    mn_edges_df
    .groupby("layer_name")["bodyId_post"]
    .unique()
    .apply(list)
    .to_dict()
)

# rename MN layer names to match 4B layer names
mn_layers_named = {
    f"{layer_name} -> MN": ids
    for layer_name, ids in mn_targets_per_layer_dict.items()
}

# load base state
import json
from copy import deepcopy

STATE_IN = INPUT_DIR / "manc_v1p2_with_manual_IR_layers.json"

with open(STATE_IN, "r", encoding="utf-8") as f:
    base_state = json.load(f)

state = deepcopy(base_state)

# find segmentation source and reuse existing
seg_source = None

for L in state["layers"]:
    if L.get("type") == "segmentation":
        src = L.get("source")
        url = src.get("url") if isinstance(src, dict) else src
        if "manc-seg-v1p2/manc-seg-v1.2" in str(url):
            seg_source = src
            break

if seg_source is None:
    raise ValueError("Segmentation source not found")


#add Mns segmentation layers
COLORS = ["#FF0000", "#00FFFF", "#FFD700", "#FF00FF", "#00FF00", "#FFA500", "#87CEEB"]

for i, (layer_name, body_ids) in enumerate(mn_layers_named.items()):
    color = COLORS[i % len(COLORS)]

    state["layers"].append({
        "type": "segmentation",
        "source": seg_source,
        "tab": "segments",
        "name": layer_name,
        "segments": [str(int(b)) for b in body_ids],
        "segmentColors": {str(int(b)): color for b in body_ids},
        "visible": True,
    })

    #save state and view 

    import urllib.parse

state["title"] = "4B IR layers with downstream MN partners"

STATE_OUT = OUTPUT_DIR / "manc_v1p2_MN.json"

with open(STATE_OUT, "w", encoding="utf-8") as f:
    json.dump(state, f, indent=2)

encoded = urllib.parse.quote(json.dumps(state, separators=(",", ":")))
NEW_URL = "https://clio-ng.janelia.org/#!" + encoded

print("Saved new state:", STATE_OUT)
print("\nNew URL:\n")
print(NEW_URL)

Saved new state: c:\Users\JHS\Documents\Python\project_folder_4B\output-MN\manc_v1p2_MN.json

New URL:
